Table users2 {
  id integer [pk]
  name varchar [not null]
  email varchar [not null]
}

Table merchandise {
  id integer [pk]
  name varchar [not null]
  stock integer [not null]
}

Table order2 {
  id integer [pk]
  user2_id integer [not null]
  merchandise_id integer [not null]
  order_count integer [not null]
}

Ref: users2.id < order2.user2_id
Ref: merchandise.id < order2.merchandise_id